// ─── CATEditor v2 Types ──────────────────────────────────────────────────────
// Clean re-exports from the shared type system.
// Deprecated v1 types (IGlossaryRule, ISpecialCharRule, etc.) are excluded.

export type {
  CATEditorRef,
  HighlightSegment,
  IKeywordsEntry,
  IKeywordsRule,
  ILinkRule,
  IMentionRule,
  IMentionUser,
  IQuoteRule,
  IQuoteRuleMapping,
  ISpellCheckRule,
  ISpellCheckValidation,
  ISuggestion,
  ITagRule,
  KeywordsAnnotation,
  LinkAnnotation,
  MooRule,
  PopoverContentRenderer,
  PopoverContentRendererProps,
  PopoverState,
  QuoteAnnotation,
  RawRange,
  RuleAnnotation,
  SpellCheckAnnotation,
  TagAnnotation,
} from '../cat-editor/types'

export {
  HighlightSegmentSchema,
  KeywordsAnnotationSchema,
  KeywordsEntrySchema,
  KeywordsRuleSchema,
  LinkAnnotationSchema,
  LinkRuleSchema,
  MentionRuleSchema,
  MentionUserSchema,
  MooRuleSchema,
  PopoverStateSchema,
  QuoteAnnotationSchema,
  QuoteRuleMappingSchema,
  QuoteRuleSchema,
  RawRangeSchema,
  RuleAnnotationSchema,
  SpellCheckAnnotationSchema,
  SpellCheckRuleSchema,
  SpellCheckValidationSchema,
  SuggestionSchema,
  TagAnnotationSchema,
  TagRuleSchema,
} from '../cat-editor/types'
