/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoLayoutSelectRouteImport } from './routes/demo/layout-select'
import { Route as DemoDetectQuotesRouteImport } from './routes/demo/detect-quotes'
import { Route as DemoCatEditorPerfRouteImport } from './routes/demo/cat-editor-perf'
import { Route as DemoCatEditorRouteImport } from './routes/demo/cat-editor'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoLayoutSelectRoute = DemoLayoutSelectRouteImport.update({
  id: '/demo/layout-select',
  path: '/demo/layout-select',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoDetectQuotesRoute = DemoDetectQuotesRouteImport.update({
  id: '/demo/detect-quotes',
  path: '/demo/detect-quotes',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoCatEditorPerfRoute = DemoCatEditorPerfRouteImport.update({
  id: '/demo/cat-editor-perf',
  path: '/demo/cat-editor-perf',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoCatEditorRoute = DemoCatEditorRouteImport.update({
  id: '/demo/cat-editor',
  path: '/demo/cat-editor',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo/cat-editor': typeof DemoCatEditorRoute
  '/demo/cat-editor-perf': typeof DemoCatEditorPerfRoute
  '/demo/detect-quotes': typeof DemoDetectQuotesRoute
  '/demo/layout-select': typeof DemoLayoutSelectRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo/cat-editor': typeof DemoCatEditorRoute
  '/demo/cat-editor-perf': typeof DemoCatEditorPerfRoute
  '/demo/detect-quotes': typeof DemoDetectQuotesRoute
  '/demo/layout-select': typeof DemoLayoutSelectRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo/cat-editor': typeof DemoCatEditorRoute
  '/demo/cat-editor-perf': typeof DemoCatEditorPerfRoute
  '/demo/detect-quotes': typeof DemoDetectQuotesRoute
  '/demo/layout-select': typeof DemoLayoutSelectRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo/cat-editor'
    | '/demo/cat-editor-perf'
    | '/demo/detect-quotes'
    | '/demo/layout-select'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo/cat-editor'
    | '/demo/cat-editor-perf'
    | '/demo/detect-quotes'
    | '/demo/layout-select'
  id:
    | '__root__'
    | '/'
    | '/demo/cat-editor'
    | '/demo/cat-editor-perf'
    | '/demo/detect-quotes'
    | '/demo/layout-select'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoCatEditorRoute: typeof DemoCatEditorRoute
  DemoCatEditorPerfRoute: typeof DemoCatEditorPerfRoute
  DemoDetectQuotesRoute: typeof DemoDetectQuotesRoute
  DemoLayoutSelectRoute: typeof DemoLayoutSelectRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/layout-select': {
      id: '/demo/layout-select'
      path: '/demo/layout-select'
      fullPath: '/demo/layout-select'
      preLoaderRoute: typeof DemoLayoutSelectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/detect-quotes': {
      id: '/demo/detect-quotes'
      path: '/demo/detect-quotes'
      fullPath: '/demo/detect-quotes'
      preLoaderRoute: typeof DemoDetectQuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/cat-editor-perf': {
      id: '/demo/cat-editor-perf'
      path: '/demo/cat-editor-perf'
      fullPath: '/demo/cat-editor-perf'
      preLoaderRoute: typeof DemoCatEditorPerfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/cat-editor': {
      id: '/demo/cat-editor'
      path: '/demo/cat-editor'
      fullPath: '/demo/cat-editor'
      preLoaderRoute: typeof DemoCatEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoCatEditorRoute: DemoCatEditorRoute,
  DemoCatEditorPerfRoute: DemoCatEditorPerfRoute,
  DemoDetectQuotesRoute: DemoDetectQuotesRoute,
  DemoLayoutSelectRoute: DemoLayoutSelectRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
